Add missing method. Fixes tests:
    tests/test_api/test_properties.py:52: in call_properties
        getattr(zenpy_object, attr_name)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = Section(id=1)

        @property
        def parent_section(self):
            """
            |  Comment: The id of the section to which this section belongs
            """
            if self.api and self.parent_section_id:
    >           return self.api._get_parent_section(self.parent_section_id)
    E           AttributeError: 'TicketApi' object has no attribute '_get_parent_section'